import React, { useState, useEffect } from 'react';
import { FileText, Download, Plus, CheckCircle2, AlertCircle, X, Printer } from 'lucide-react';
import Title from '../components/Title.jsx';
import api from '../services/api.js';
import { useToast } from '../context/ToastContext.jsx';

export default function Reports() {
  const toast = useToast();
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(false);
  const [showGenerateModal, setShowGenerateModal] = useState(false);
  const [reportType, setReportType] = useState('financial_summary');
  const [format, setFormat] = useState('csv');
  const [generating, setGenerating] = useState(false);
  const [message, setMessage] = useState('');

  const fetchReports = async () => {
    setLoading(true);
    try {
      const res = await api.get('/reports/');
      if (res.data) setReports(res.data);
    } catch (err) {
      toast.error('Failed to load reports: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, []);

  const handleGenerate = async (e) => {
    e.preventDefault();
    setGenerating(true);
    setMessage('');
    try {
      const res = await api.post('/reports/generate', { type: reportType, format });
      const successMsg = res.message || 'Report generated successfully.';
      setMessage(successMsg);
      toast.success(successMsg);
      setShowGenerateModal(false);
      fetchReports();
    } catch (err) {
      toast.error('Report generation failed: ' + err.message);
    } finally {
      setGenerating(false);
    }
  };

  const handleDownload = async (report) => {
    try {
      const res = await api.get(`/reports/${report.id}/download`);
      if (res.blob) {
        const url = window.URL.createObjectURL(res.blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = res.filename || `${report.report_id}.${report.format}`;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
        toast.success(`Downloaded ${report.report_id}`);
      }
    } catch (err) {
      toast.error('Failed to download report: ' + err.message);
    }
  };

  return (
    <>
      <Title
        title="Official Reports & Audit Dossiers"
        text="Compile auditable financial disclosures, anomaly dossiers, and executive briefings."
        action={
          <div style={{ display: 'flex', gap: '10px' }}>
            <button className="primary" onClick={() => window.print()} style={{ background: 'var(--surface, #FFFFFF)', color: 'var(--text, #20282D)', border: '1px solid var(--border, #DDDCD6)' }}>
              <Printer size={16} /> Print Briefing
            </button>
            <button className="primary" onClick={() => setShowGenerateModal(true)}>
              <Plus size={16} /> Generate New Report
            </button>
          </div>
        }
      />

      {message && (
        <div
          style={{
            marginBottom: '16px',
            padding: '12px 18px',
            background: '#ecfdf5',
            color: '#065f46',
            borderRadius: '8px',
            fontSize: '13px',
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
          }}
        >
          <CheckCircle2 size={16} />
          <span>{message}</span>
        </div>
      )}

      {/* Reports Table */}
      <section className="card table">
        <table>
          <thead>
            <tr>
              <th>Report ID</th>
              <th>Report Title</th>
              <th>Type</th>
              <th>Format</th>
              <th>Generated By</th>
              <th>Created Date</th>
              <th style={{ textAlign: 'right' }}>Actions</th>
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr>
                <td colSpan={7} style={{ textAlign: 'center', padding: '36px', color: '#64748b' }}>
                  Loading generated reports...
                </td>
              </tr>
            ) : reports.length === 0 ? (
              <tr>
                <td colSpan={7} style={{ textAlign: 'center', padding: '36px', color: '#64748b' }}>
                  No reports compiled yet. Click "Generate New Report" to create an audit summary.
                </td>
              </tr>
            ) : (
              reports.map((r) => (
                <tr key={r.id}>
                  <td>
                    <b style={{ color: 'var(--primary)' }}>{r.report_id}</b>
                  </td>
                  <td style={{ fontWeight: 600 }}>{r.title}</td>
                  <td style={{ textTransform: 'capitalize', fontSize: '12px' }}>
                    {r.report_type.replace(/_/g, ' ')}
                  </td>
                  <td>
                    <span
                      style={{
                        padding: '2px 6px',
                        background: '#f1f5f9',
                        borderRadius: '4px',
                        fontSize: '11px',
                        fontWeight: 700,
                        textTransform: 'uppercase',
                      }}
                    >
                      {r.format}
                    </span>
                  </td>
                  <td>{r.generator?.name || 'System Auditor'}</td>
                  <td style={{ fontSize: '12px', color: '#64748b' }}>
                    {new Date(r.created_at).toLocaleString()}
                  </td>
                  <td style={{ textAlign: 'right' }}>
                    <button className="link" onClick={() => handleDownload(r)}>
                      <Download size={14} /> Download
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </section>

      {/* Generate Report Modal */}
      {showGenerateModal && (
        <div className="overlay" onClick={() => setShowGenerateModal(false)}>
          <div
            style={{
              width: '90%',
              maxWidth: '500px',
              background: '#fff',
              margin: 'auto',
              borderRadius: 'var(--radius-lg, 10px)',
              border: '1px solid var(--border, #DDDCD6)',
              padding: '24px',
              boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
            }}
            onClick={(e) => e.stopPropagation()}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
              <h2 style={{ margin: 0, fontSize: '18px', fontWeight: 800 }}>Compile Audit Report</h2>
              <button onClick={() => setShowGenerateModal(false)}>
                <X size={20} />
              </button>
            </div>

            <form onSubmit={handleGenerate} style={{ display: 'grid', gap: '14px' }}>
              <div>
                <label style={{ display: 'block', fontSize: '12px', fontWeight: 600, color: '#475569', marginBottom: '4px' }}>
                  Report Domain Scope
                </label>
                <select
                  value={reportType}
                  onChange={(e) => setReportType(e.target.value)}
                  style={{ width: '100%' }}
                >
                  <option value="financial_summary">Financial Records & Allocation Dossier</option>
                  <option value="anomaly_report">Anomaly &amp; Outlier Assessment</option>
                  <option value="case_report">Case Investigation & Workflow Registry</option>
                  <option value="complaint_report">Citizen Grievances & NLP Urgency Log</option>
                </select>
              </div>

              <div>
                <label style={{ display: 'block', fontSize: '12px', fontWeight: 600, color: '#475569', marginBottom: '4px' }}>
                  Export Format
                </label>
                <select
                  value={format}
                  onChange={(e) => setFormat(e.target.value)}
                  style={{ width: '100%' }}
                >
                  <option value="csv">CSV Spreadsheet (.csv)</option>
                  <option value="json">Structured JSON (.json)</option>
                </select>
              </div>

              <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '10px', marginTop: '12px' }}>
                <button
                  type="button"
                  onClick={() => setShowGenerateModal(false)}
                  style={{ padding: '8px 16px', borderRadius: '8px', border: '1px solid #cbd5e1' }}
                >
                  Cancel
                </button>
                <button type="submit" className="primary" disabled={generating}>
                  {generating ? 'Generating...' : 'Compile Report'}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </>
  );
}
